### ISSUE TITLE
Warning: ScrollView doesn't take rejection well - scrolls anyway

### ISSUE THREAD

**Issue by lrettig** [gcanti/tcomb-form-native#111] opened 2016-02-02 16:59 UTC
I get this error continually on a form that lives inside a ScrollView. It appears to be due to this issue: facebook/react-native#1501.

It seems there is at least one proposed solution for TextInput inside of a ScrollView: cf. https://github.com/facebook/react-native/issues/1501#issuecomment-169099731

Can this change be made at the tcomb-form level?

Thanks.

**Comment by BilalBudhani** [comment] 2016-02-03 08:59
I've been facing this issue as well. Somebody also suggested [this solution](https://github.com/facebook/react-native/issues/1501#issuecomment-170537185) on the thread but it doesn't work for me.

**Comment by alvaromb** [comment] 2016-02-04 08:03
Hello!

I think this should be fixed at React Native level, not on ``tcomb-form-native``. We shouldn't patch RN as long as it's only a warning and doesn't break the library. Anyway, you can drop a custom ``template`` or ``factory`` and try to implement the fix but IMHO it would be a waste of time because ``TextInput`` behaviour is not affected by the warning.

**Closed by alvaromb** 2016-02-04 08:03 UTC

**Comment by lrettig** [comment] 2016-02-04 15:37
Actually the behavior does change, it's not just the warning. If you have a form rendered on top of a ScrollView, then when you try to move from one `TextInput` to the next by tapping, the warning fires, and the next field doesn't get focus. You have to tap twice. It makes forms very annoying to use.

For the record I also tried implementing the fix I mentioned above and it didn't work.

**Comment by alvaromb** [comment] 2016-02-04 15:43
Can't reproduce your issue @lrettig. Testing right now with the latest React Native and ``tcomb-form-native`` versions. I do get the warnings, but the ``TextInput`` gets focused. I would like to bring @gcanti to confirm my point, this should be a RN fix, not with this library.

**Comment by alvaromb** [comment] 2016-02-04 15:50
Implementing this fix https://github.com/facebook/react-native/issues/1501#issuecomment-169099731 would mean ``tcomb-form-native`` should include the patched version of ``TextInput``, something that I strongly discourage because it could add potentially dangerous mismatch between the RN ``TextInput`` and ours. 

Best thing we can do is to try to fix this into RN and send a PR there. This bug it's been around for a while right now.

**Comment by gcanti** [comment] 2016-02-04 16:03
I agree with @alvaromb, this issue should be fixed upstream.

**Comment by lrettig** [comment] 2016-02-04 16:52
Thanks so much for looking into this, guys. If I can put together a quick demo to show the issue I'm talking about (textinput not getting focus on tap), I'll do that and share it here.

**Comment by coderwin** [comment] 2016-03-15 04:27
"If you have a form rendered on top of a ScrollView, then when you try to move from one TextInput to the next by tapping, the warning fires, and the next field doesn't get focus. You have to tap twice." 
+1, How to fix?

**Comment by coderwin** [comment] 2016-03-15 06:36
ScrollView ==> set keyboardShouldPersistTaps={true} that is all OK. **@lrettig**

**Comment by alvaromb** [comment] 2016-03-15 08:02
It's an upstream issue @coderwin
