### ISSUE TITLE
Password is visible on Android

### ISSUE THREAD

**Issue by Bob1993** [gcanti/tcomb-form-native#136] opened 2016-03-29 02:37 UTC
### Version

Tell us which versions you are using:

- tcomb-form-native v0.4.0
- react-native v0.22.2
- platform Android

### Problem  
the password show visible content though I use
`password: true`
`secureTextEntry: true`.

**Comment by rogerroelofs** [comment] 2016-03-31 14:58
I had the same problem and had to remove the keyboardtype attribute to get it to display properly.  This is technically not a tcomb-form-native problem since the lib is just passing the attributes through to RN

**Comment by gcanti** [comment] 2016-03-31 15:02
> This is technically not a tcomb-form-native problem since the lib is just passing the attributes through to RN

Thanks @rogerroelofs for clarifying.

**Comment by alvaromb** [comment] 2016-05-04 07:06
Does this still happen with newer RN versions? Can't reproduce it! Closing by now, please feel free to ping me if it still happens.

**Closed by alvaromb** 2016-05-04 07:06 UTC
Labels: Type: Upstream Issue (react-native)

**Comment by Bob1993** [comment] 2016-05-04 11:00
@alvaromb  I'm too busy to respond here recently, thanks for your help

**Comment by abuammar** [comment] 2017-11-01 07:13
Problem

the password show visible content though I use
password: true
secureTextEntry: true.
