### ISSUE TITLE
Double click to focus with ScrollView

### ISSUE THREAD

**Issue by mjniuz** [gcanti/tcomb-form-native#226] opened 2016-09-04 14:39 UTC
### Version

Tell us which versions you are using:

- tcomb-form-native v0.6.0
- react-native v0.31.0

### Expected behaviour

One click text input to focus

### Actual behaviour

It need double click to focus to some text input

### Steps to reproduce

Here is my code
`<ScrollView>
                    <View style={inStyle.form}>
                        <Form
                            ref="form"
                            type={RegisterData}
                            options={options}
                        />
                    </View>
                </ScrollView>`

### Stack trace and console log

Hint: it would help a lot if you enable the debugger ("Pause on exceptions" in the "Source" panel of Chrome dev tools) and spot the place where the error is thrown

```
```

**Comment by gcanti** [comment] 2016-09-04 16:16
Duplicate of https://github.com/gcanti/tcomb-form-native/issues/181

**Closed by gcanti** 2016-09-04 16:16 UTC
Labels: Type: Duplicate
